#############################################################################
# Makefile for building: EVMPulseDet
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? 6? 21 11:30:43 2014
# Project:  EVMPulseDetect.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile EVMPulseDetect.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/opencv -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 /usr/lib64/libopencv_calib3d.so /usr/lib64/libopencv_contrib.so /usr/lib64/libopencv_core.so /usr/lib64/libopencv_features2d.so /usr/lib64/libopencv_flann.so /usr/lib64/libopencv_gpu.so /usr/lib64/libopencv_highgui.so /usr/lib64/libopencv_imgproc.so /usr/lib64/libopencv_legacy.so /usr/lib64/libopencv_ml.so /usr/lib64/libopencv_nonfree.so /usr/lib64/libopencv_objdetect.so /usr/lib64/libopencv_photo.so /usr/lib64/libopencv_stitching.so /usr/lib64/libopencv_superres.so /usr/lib64/libopencv_ts.so /usr/lib64/libopencv_video.so /usr/lib64/libopencv_videostab.so -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		facedetect.cpp \
		facetrack.cpp \
		SpatialFilter.cpp \
		colormagnify.cpp \
		featuresdetect.cpp moc_mainwindow.cpp \
		moc_facedetect.cpp \
		moc_facetrack.cpp \
		moc_colormagnify.cpp \
		moc_featuresdetect.cpp \
		qrc_icons.cpp
OBJECTS       = main.o \
		mainwindow.o \
		facedetect.o \
		facetrack.o \
		SpatialFilter.o \
		colormagnify.o \
		featuresdetect.o \
		moc_mainwindow.o \
		moc_facedetect.o \
		moc_facetrack.o \
		moc_colormagnify.o \
		moc_featuresdetect.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EVMPulseDetect.pro
QMAKE_TARGET  = EVMPulseDet
DESTDIR       = 
TARGET        = EVMPulseDet

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EVMPulseDetect.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -o Makefile EVMPulseDetect.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile EVMPulseDetect.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EVMPulseDet1.0.0 || $(MKDIR) .tmp/EVMPulseDet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EVMPulseDet1.0.0/ && $(COPY_FILE) --parents mainwindow.h facedetect.h facetrack.h SpatialFilter.h colormagnify.h featuresdetect.h .tmp/EVMPulseDet1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/EVMPulseDet1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp facedetect.cpp facetrack.cpp SpatialFilter.cpp colormagnify.cpp featuresdetect.cpp .tmp/EVMPulseDet1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/EVMPulseDet1.0.0/ && (cd `dirname .tmp/EVMPulseDet1.0.0` && $(TAR) EVMPulseDet1.0.0.tar EVMPulseDet1.0.0 && $(COMPRESS) EVMPulseDet1.0.0.tar) && $(MOVE) `dirname .tmp/EVMPulseDet1.0.0`/EVMPulseDet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EVMPulseDet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_facedetect.cpp moc_facetrack.cpp moc_colormagnify.cpp moc_featuresdetect.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_facedetect.cpp moc_facetrack.cpp moc_colormagnify.cpp moc_featuresdetect.cpp
moc_mainwindow.cpp: facedetect.h \
		facetrack.h \
		colormagnify.h \
		SpatialFilter.h \
		featuresdetect.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_facedetect.cpp: facedetect.h
	/usr/bin/moc $(DEFINES) $(INCPATH) facedetect.h -o moc_facedetect.cpp

moc_facetrack.cpp: facetrack.h
	/usr/bin/moc $(DEFINES) $(INCPATH) facetrack.h -o moc_facetrack.cpp

moc_colormagnify.cpp: SpatialFilter.h \
		colormagnify.h
	/usr/bin/moc $(DEFINES) $(INCPATH) colormagnify.h -o moc_colormagnify.cpp

moc_featuresdetect.cpp: featuresdetect.h
	/usr/bin/moc $(DEFINES) $(INCPATH) featuresdetect.h -o moc_featuresdetect.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		icons/gtk-help.png \
		icons/gnome-stock-mail-new.png \
		icons/gtk-goto-top.png \
		icons/gtk-save-as.png \
		icons/mail_forward.png \
		icons/revert.png \
		icons/stock_bottom.png \
		icons/stock_help.png \
		icons/tab_new.png \
		icons/qt.png \
		icons/document-open-recent.png \
		icons/stock_properties.png \
		icons/window-new.png \
		icons/remove.png \
		icons/stock_mail-compose.png \
		icons/stock_help-add-bookmark.png \
		icons/object-flip-vertical.png \
		icons/filesaveas.png \
		icons/stock_text_justify.png \
		icons/go-home.png \
		icons/gtk-media-forward-ltr.png \
		icons/gtk-find.png \
		icons/edit-undo.png \
		icons/player_end.png \
		icons/stock_text_unindent.png \
		icons/redhat-home.png \
		icons/edit-cut.png \
		icons/media-seek-backward.png \
		icons/text_strike.png \
		icons/gnome-searchtool.png \
		icons/mail-mark-junk.png \
		icons/stock_home.png \
		icons/player_eject.png \
		icons/stock_text-strikethrough.png \
		icons/stock_mail-reply.png \
		icons/list-add.png \
		icons/gtk-sort-descending.png \
		icons/fileopen.png \
		icons/stock_text_indent.png \
		icons/gnome-lockscreen.png \
		icons/gtk-about.png \
		icons/help.png \
		icons/view-restore.png \
		icons/gnome-run.png \
		icons/stock_new-appointment.png \
		icons/application-exit.png \
		icons/viewmag1.png \
		icons/stock_new-dir.png \
		icons/stock_mail-send-receive.png \
		icons/stock_media-play.png \
		icons/gnome-stock-mail-fwd.png \
		icons/finish.png \
		icons/stock_print-preview.png \
		icons/go-first.png \
		icons/mail-mark-notjunk.png \
		icons/gtk-save.png \
		icons/stock_last.png \
		icons/edit-paste.png \
		icons/gtk-leave-fullscreen.png \
		icons/gtk-home.png \
		icons/gtk-zoom-fit.png \
		icons/document-save.png \
		icons/gtk-zoom-100.png \
		icons/editdelete.png \
		icons/gtk-edit.png \
		icons/lock.png \
		icons/reload_page.png \
		icons/gtk-strikethrough.png \
		icons/gtk-properties.png \
		icons/gtk-indent-rtl.png \
		icons/stock_save-as.png \
		icons/call-stop.png \
		icons/gtk-spell-check.png \
		icons/gtk-italic.png \
		icons/redo.png \
		icons/gnome-stock-text-indent.png \
		icons/kfm_home.png \
		icons/filenew.png \
		icons/player_stop.png \
		icons/format-text-direction-ltr.png \
		icons/go-jump.png \
		icons/go-previous.png \
		icons/forward.png \
		icons/gtk-revert-to-saved-ltr.png \
		icons/mail_new.png \
		icons/window_new.png \
		icons/reload3.png \
		icons/gtk-go-forward-rtl.png \
		icons/stock_media-fwd.png \
		icons/stock_new-address-book.png \
		icons/stock_search-and-replace.png \
		icons/player_pause.png \
		icons/gtk-media-pause.png \
		icons/reload.png \
		icons/gnome-stock-mail-rpl.png \
		icons/gtk-bold.png \
		icons/player_record.png \
		icons/stock_media-rec.png \
		icons/stock_left.png \
		icons/stock_save.png \
		icons/edit-copy.png \
		icons/gtk-cancel.png \
		icons/document-print-preview.png \
		icons/format-text-strikethrough.png \
		icons/gnome-session-logout.png \
		icons/folder-new.png \
		icons/start.png \
		icons/stock_fullscreen.png \
		icons/centrejust.png \
		icons/view-sort-ascending.png \
		icons/gtk-close.png \
		icons/gtk-justify-left.png \
		icons/stock_media-pause.png \
		icons/editpaste.png \
		icons/stock_new-bcard.png \
		icons/edit-redo.png \
		icons/gtk-fullscreen.png \
		icons/view-sort-descending.png \
		icons/filefind.png \
		icons/stock_text_italic.png \
		icons/zoom-best-fit.png \
		icons/next.png \
		icons/up.png \
		icons/viewmag+.png \
		icons/gtk-add.png \
		icons/exit.png \
		icons/gtk-remove.png \
		icons/mail_replyall.png \
		icons/edit-find.png \
		icons/stock_spam.png \
		icons/media-playback-stop.png \
		icons/zoom-original.png \
		icons/gtk-print-preview.png \
		icons/add.png \
		icons/gtk-media-forward-rtl.png \
		icons/stock_stop.png \
		icons/system-run.png \
		icons/format-justify-fill.png \
		icons/mail-mark-unread.png \
		icons/window_nofullscreen.png \
		icons/stock_media-stop.png \
		icons/edit-clear.png \
		icons/fileprint.png \
		icons/stock_mail-send.png \
		icons/stock_mail-forward.png \
		icons/stock_first.png \
		icons/gtk-unindent-ltr.png \
		icons/document-open.png \
		icons/stock_paste.png \
		icons/format-text-underline.png \
		icons/stock_undo.png \
		icons/system-search.png \
		icons/stock_leave-fullscreen.png \
		icons/help-contents.png \
		icons/gtk-cut.png \
		icons/down.png \
		icons/call-start.png \
		icons/system-log-out.png \
		icons/gtk-paste.png \
		icons/gtk-print.png \
		icons/list-remove.png \
		icons/document-new.png \
		icons/system-lock-screen.png \
		icons/text_bold.png \
		icons/format-justify-center.png \
		icons/edit-find-replace.png \
		icons/zoom-in.png \
		icons/contact-new.png \
		icons/gtk-execute.png \
		icons/gtk-media-record.png \
		icons/bottom.png \
		icons/stock_print-setup.png \
		icons/gtk-select-all.png \
		icons/media-skip-forward.png \
		icons/gtk-goto-first-ltr.png \
		icons/filequickprint.png \
		icons/stock_copy.png \
		icons/gtk-go-back-rtl.png \
		icons/format-justify-right.png \
		icons/stock_text_underlined.png \
		icons/editclear.png \
		icons/stock_mail-reply-to-all.png \
		icons/stock_zoom-out.png \
		icons/gtk-goto-bottom.png \
		icons/mail_spam.png \
		icons/stock_media-rew.png \
		icons/gtk-open.png \
		icons/address-book-new.png \
		icons/view-fullscreen.png \
		icons/bookmark_add.png \
		icons/player_play.png \
		icons/stock_new-text.png \
		icons/mail-reply-sender.png \
		icons/media-playback-start.png \
		icons/text_italic.png \
		icons/gtk-indent-ltr.png \
		icons/media-record.png \
		icons/object-rotate-right.png \
		icons/top.png \
		icons/format-text-direction-rtl.png \
		icons/mail-send.png \
		icons/window-close.png \
		icons/stock_file-properites.png \
		icons/bookmarks_list_add.png \
		icons/stock_top.png \
		icons/mail-send-receive.png \
		icons/media-eject.png \
		icons/stock_text_center.png \
		icons/stock_about.png \
		icons/go-bottom.png \
		icons/gnome-stock-text-unindent.png \
		icons/xfce-system-exit.png \
		icons/back.png \
		icons/bookmark-new.png \
		icons/stock_text_right.png \
		icons/gtk-media-previous-ltr.png \
		icons/tools-check-spelling.png \
		icons/search.png \
		icons/format-indent-more.png \
		icons/stock_redo.png \
		icons/gtk-find-and-replace.png \
		icons/editcut.png \
		icons/gtk-media-rewind-rtl.png \
		icons/window_fullscreen.png \
		icons/gtk-jump-to-ltr.png \
		icons/gtk-zoom-in.png \
		icons/find.png \
		icons/mail-mark-read.png \
		icons/help-faq.png \
		icons/gtk-justify-right.png \
		icons/player_start.png \
		icons/gtk-justify-center.png \
		icons/stock_zoom-in.png \
		icons/gtk-sort-ascending.png \
		icons/stock_refresh.png \
		icons/insert-object.png \
		icons/gtk-unindent-rtl.png \
		icons/gtk-media-next-rtl.png \
		icons/view-refresh.png \
		icons/stock_print.png \
		icons/stock_media-prev.png \
		icons/gtk-goto-last-ltr.png \
		icons/gnome-stock-mail-snd.png \
		icons/stock_spellcheck.png \
		icons/gtk-zoom-out.png \
		icons/viewmagfit.png \
		icons/document-revert.png \
		icons/zoom-out.png \
		icons/process-stop.png \
		icons/edit-select-all.png \
		icons/gtk-goto-first-rtl.png \
		icons/gtk-new.png \
		icons/stock_search.png \
		icons/gtk-undo-ltr.png \
		icons/insert-text.png \
		icons/format-indent-less.png \
		icons/stock_new-tab.png \
		icons/go-down.png \
		icons/stock_zoom-1.png \
		icons/player_fwd.png \
		icons/stock_cut.png \
		icons/format-text-italic.png \
		icons/viewmag-.png \
		icons/gohome.png \
		icons/mail-message-new.png \
		icons/gtk-media-previous-rtl.png \
		icons/document-print.png \
		icons/stock_add-bookmark.png \
		icons/reload_all_tabs.png \
		icons/stop.png \
		icons/rightjust.png \
		icons/format-text-bold.png \
		icons/gtk-go-forward-ltr.png \
		icons/gnome-shutdown.png \
		icons/stock_text_bold.png \
		icons/format-justify-left.png \
		icons/stock_close.png \
		icons/gtk-refresh.png \
		icons/system-shutdown.png \
		icons/object-rotate-left.png \
		icons/stock_up.png \
		icons/go-top.png \
		icons/media-playback-pause.png \
		icons/document-send.png \
		icons/undo.png \
		icons/gtk-go-down.png \
		icons/mail_send.png \
		icons/gtk-copy.png \
		icons/mail-mark-important.png \
		icons/document-page-setup.png \
		icons/previous.png \
		icons/insert-link.png \
		icons/stock_media-next.png \
		icons/gnome-logout.png \
		icons/document-save-as.png \
		icons/filesave.png \
		icons/stock_delete.png \
		icons/stock_new-window.png \
		icons/go-last.png \
		icons/stock_zoom-page.png \
		icons/text_under.png \
		icons/mail_reply.png \
		icons/insert-image.png \
		icons/help-about.png \
		icons/edit-delete.png \
		icons/kfind.png \
		icons/stock_select-all.png \
		icons/gtk-media-stop.png \
		icons/gtk-goto-last-rtl.png \
		icons/object-flip-horizontal.png \
		icons/document-properties.png \
		icons/gtk-clear.png \
		icons/gtk-redo-ltr.png \
		icons/folder_new.png \
		icons/xfce-system-lock.png \
		icons/zoom-fit-best.png \
		icons/appointment.png \
		icons/gtk-stop.png \
		icons/mail-forward.png \
		icons/gtk-jump-to-rtl.png \
		icons/gtk-media-next-ltr.png \
		icons/gtk-delete.png \
		icons/gtk-justify-fill.png \
		icons/go-next.png \
		icons/gtk-go-up.png \
		icons/editcopy.png \
		icons/media-skip-backward.png \
		icons/mail-reply-all.png \
		icons/go-up.png \
		icons/stock_down.png \
		icons/gtk-revert-to-saved-rtl.png \
		icons/gtk-go-back-ltr.png \
		icons/tab-new.png \
		icons/stock_right.png \
		icons/gtk-underline.png \
		icons/gtk-media-rewind-ltr.png \
		icons/leftjust.png \
		icons/gtk-quit.png \
		icons/appointment-new.png \
		icons/media-seek-forward.png \
		icons/stock_text_left.png \
		icons/gtk-media-play-ltr.png \
		icons/player_rew.png
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		facedetect.h \
		facetrack.h \
		colormagnify.h \
		SpatialFilter.h \
		featuresdetect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		facedetect.h \
		facetrack.h \
		colormagnify.h \
		SpatialFilter.h \
		featuresdetect.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

facedetect.o: facedetect.cpp facedetect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facedetect.o facedetect.cpp

facetrack.o: facetrack.cpp facetrack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facetrack.o facetrack.cpp

SpatialFilter.o: SpatialFilter.cpp SpatialFilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpatialFilter.o SpatialFilter.cpp

colormagnify.o: colormagnify.cpp colormagnify.h \
		SpatialFilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colormagnify.o colormagnify.cpp

featuresdetect.o: featuresdetect.cpp featuresdetect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o featuresdetect.o featuresdetect.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_facedetect.o: moc_facedetect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_facedetect.o moc_facedetect.cpp

moc_facetrack.o: moc_facetrack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_facetrack.o moc_facetrack.cpp

moc_colormagnify.o: moc_colormagnify.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_colormagnify.o moc_colormagnify.cpp

moc_featuresdetect.o: moc_featuresdetect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_featuresdetect.o moc_featuresdetect.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

